import { Row } from '@src/shared/types';
import { CUSTOMER_MAP } from '@src/shared/constants/customers';
import { FormFieldsSchema } from '../types';

export const MONTHS_IN_QUARTER = 3;
export const ADDITIONAL_DAYS_OUT_QUARTER = 10;
export const ALLOCATION_FIELDS_NAMES: Array<keyof Row> = [
  'usage_confirm_date_q1',
  'usage_confirm_date_q2',
  'usage_confirm_date_q3',
  'usage_confirm_date_q4',
  'usage_confirm_flag_q1',
  'usage_confirm_flag_q2',
  'usage_confirm_flag_q3',
  'usage_confirm_flag_q4',
  'allocation_kib_usage',
  'allocation_smb_usage',
  'allocation_rb_usage',
  'allocation_kc_usage',
  'allocation_other_usage',
  'allocation_kib_comment',
  'allocation_smb_comment',
  'allocation_rb_comment',
  'allocation_kc_comment',
  'allocation_other_comment',
];
export const ALLOCATION_FIELDS_NAMES_USAGE: Array<keyof Row> = [
  'allocation_kib_usage',
  'allocation_smb_usage',
  'allocation_rb_usage',
  'allocation_kc_usage',
  'allocation_other_usage',
];

type SchemaNameMap = {
  [key: string]: {
    title: string;
    schemaOrder: number;
    key: string;
  };
};

export const SCHEMA_NAME_MAP: SchemaNameMap = {
  BASE_MODEL_SCHEMA: { key: 'BASE_MODEL_SCHEMA', title: 'Базовые атрибуты', schemaOrder: 2 },
  ACTIVE_MODEL_SCHEMA: {
    key: 'ACTIVE_MODEL_SCHEMA',
    title: 'Активные атрибуты',
    schemaOrder: 1,
  },
  NOT_ACTIVE_MODEL_SCHEMA: {
    key: 'NOT_ACTIVE_MODEL_SCHEMA',
    title: 'Атрибуты неактивной модели',
    schemaOrder: 3,
  },
  RATING_SYSTEM_MODEL_SCHEMA: {
    key: 'RATING_SYSTEM_MODEL_SCHEMA',
    title: 'Атрибуты рейтинговой системы',
    schemaOrder: 4,
  },
  RATING_SYSTEM_REGULATOR_APPROVE_MODEL_SCHEMA: {
    key: 'RATING_SYSTEM_REGULATOR_APPROVE_MODEL_SCHEMA',
    title: 'Атрибуты рейтинговой системы, подлежащей согласованию Регулятором',
    schemaOrder: 5,
  },
  REST_MODEL_SCHEMA: { key: 'REST_MODEL_SCHEMA', title: 'Прочие атрибуты', schemaOrder: 8 },
  VALIDATION_MODEL_SCHEMA: {
    key: 'VALIDATION_MODEL_SCHEMA',
    title: 'Атрибуты валидации',
    schemaOrder: 9,
  },
};

export const BASE_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'model_name_validation',
    required: true,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'model_desc',
    required: true,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'business_customer',
    required: true,
    maxLength: 255,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'business_customer_departament',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'group_company',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'significance_validity',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'model_name',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.DADM],
  },
  {
    name: 'ds_department',
    required: false,
    maxLength: 255,
    customers: [CUSTOMER_MAP.DADM, CUSTOMER_MAP.UMRV],
  },
  {
    name: 'ds_stream',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'product_name',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'developing_model_reason',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'model_algorithm',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'rfd',
    required: false,
    customers: [CUSTOMER_MAP.DADM],
    maxLength: 250,
  },
  {
    name: 'provides_piloting',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'operational_monitoring',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'analytical_monitoring',
    customers: [CUSTOMER_MAP.DADM],
    required: false,
  },
  {
    name: 'model_data_07k_control',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'model_data_07k_control_epic',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'target',
    required: false,
    customers: [CUSTOMER_MAP.DADM],
    maxLength: 100,
  },
  {
    name: 'model_changes_info',
    required: false,
    customers: [CUSTOMER_MAP.DADM],
    maxLength: 250,
  },
  // Создание модели (ADD): getFormFields берёт только BASE_MODEL_SCHEMA — иначе полей нет на странице.
  {
    name: 'implementation_segment',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'remove_decision',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'segment_name',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'validation_report_approve_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_04_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_05a',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_07',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'customer_model_id',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_09',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_11_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_12_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'output_table',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'allocation_assessment_parameters',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'runtime_subsystem',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'developing_end_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'rs_model_decommiss_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'developing_start_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_04',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_05',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'data_completion_of_stage_05a',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_07_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'release',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_11',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_epic_12',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'date_of_introduction_into_operation',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'allocation_assessment_class',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'deploy_team',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'buiseness_process_name',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'deploy_system',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'dev_team',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'project_ref',
    required: false,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV],
  },
];

export const ACTIVE_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'model_name_validation',
    required: true,
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'group_company',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'model_type',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'model_desc',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'significance_validity',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    valueConditions: [
      {
        value: 'Высокая',
        conditions: [
          {
            classification_of_rs_by_order_of_application_within_pvr:
              'Рейтинговые системы, подлежащие согласованию Регулятором',
          },
        ],
      },
    ],
  },
  {
    name: 'business_model_risk_subtype',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: false,
    maxLength: 250,
  },
  {
    name: 'responsible_for_significance_validity',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    maxLength: 250,
  },
  {
    name: 'implementation_segment',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    maxLength: 250,
  },
  {
    name: 'business_customer',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    maxLength: 250,
  },
  {
    name: 'business_customer_departament',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: false,
    requireConditions: [{ active_model: '1' }],
  },
  {
    name: 'implementation_validity',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
  },
  {
    name: 'validity_approve',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    maxLength: 250,
  },
  {
    name: 'ds_department',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: false,
    requireConditions: [{ active_model: '1' }],
    maxLength: 250,
  },
  {
    name: 'developing_report',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: false,
    requireConditions: [{ active_model: '1' }],
    maxLength: 250,
  },
  {
    name: 'model_risk_type',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    required: true,
    maxLength: 250,
  },
  ///
  {
    name: 'rating_model',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
      },
    ],
    valueConditions: [
      {
        value: 'Да',
        conditions: [{ model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' }],
      },
    ],
    disabledConditions: [
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
      },
    ],
    enabledByValueConditions: [
      {
        value: 'Да',
        conditions: [{ model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' }],
      },
    ],
    maxLength: 250,
  },
  {
    name: 'model_version',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_changes_info',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
    maxLength: 250,
  },
  {
    name: 'developing_end_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_id',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'update_date',
    required: false,
    alwaysDisabled: true,
    customers: [CUSTOMER_MAP.UMRV],
  },
];

export const NOT_ACTIVE_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'remove_date_validation',
    requireConditions: ['wasPreviouslyActiveModel'],
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
  {
    name: 'remove_decision',
    requireConditions: ['wasPreviouslyActiveModel'],
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
];

export const RATING_SYSTEM_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'rating_system_name',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'classification_of_rs_by_order_of_application_within_pvr',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  /// Степень регуляторного надзора
  {
    name: 'degree_of_regulatory_supervision',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
    optionConditions: [
      {
        // Уровень значимости Модели
        connected_field: 'significance_validity',
        value: 'Высокая',
        options: ['Высокая', 'Средняя'],
      },
    ],
    autoCompleteConditions: [
      {
        value: 'Высокая',
        conditions: [
          {
            significance_validity: 'Высокая',
          },
        ],
      },
    ],
    valueConditions: [
      {
        value: 'Высокая',
        conditions: [
          {
            model_type: 'Модели ВПОДК',
            model_risk_type: 'Кредитный риск',
            classification_of_rs_by_order_of_application_within_pvr:
              'Рейтинговые системы, подлежащие согласованию Регулятором',
          },
          {
            model_type: 'Риск-модели',
            model_risk_type: 'Кредитный риск',
            rating_model: 'Да',
            classification_of_rs_by_order_of_application_within_pvr:
              'Рейтинговые системы, подлежащие согласованию Регулятором',
          },
        ],
      },
    ],
  },
  {
    // уровень значимости
    name: 'significance_validity',
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    valueConditions: [
      {
        value: 'Высокая',
        conditions: [
          {
            classification_of_rs_by_order_of_application_within_pvr:
              'Рейтинговые системы, подлежащие согласованию Регулятором',
          },
        ],
      },
    ],
  },
  {
    name: 'description_rating_system',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'model_indicator',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'calibration_version',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'calibration_date',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'materiality_rate',
    // Уровень материальности
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск', impact_coverage: '' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        impact_coverage: '',
      },
    ],
    valueConditions: [
      {
        value: 'Высокий',
        conditions: [
          {
            significance_validity: 'Высокая',
            degree_of_regulatory_supervision: 'Средняя',
            impact_coverage: '',
          },
        ],
      },
      {
        value: '',
        conditions: [
          {
            impact_coverage: 'Высокий',
          },
          {
            impact_coverage: 'Средний',
          },
          {
            impact_coverage: 'Низкий',
          },
        ],
      },
    ],
  },
  {
    name: 'impact_coverage',
    // охват последствий
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск', materiality_rate: '' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        materiality_rate: '',
      },
    ],
    valueConditions: [
      {
        value: 'Высокий',
        conditions: [
          {
            significance_validity: 'Высокая',
            degree_of_regulatory_supervision: 'Средняя',
            materiality_rate: '',
          },
        ],
      },
      {
        value: '',
        conditions: [
          {
            materiality_rate: 'Высокий',
          },
          {
            materiality_rate: 'Средний',
          },
          {
            materiality_rate: 'Низкий',
          },
        ],
      },
    ],
  },
  {
    name: 'model_id_from_model_owner',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'classification_rs_algorithm_by_asset_classes',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'credit_risk_component',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'goals_using_results_of_work_rs',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'name_and_version_rating_system',
    maxLength: 250,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      { model_type: 'Модели ВПОДК', model_risk_type: 'Кредитный риск' },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
      },
    ],
  },
  {
    name: 'identifier_model_algorithm_for_rwa',
    required: false,
    maxLength: 250,
  },
  {
    name: 'segment_name',
    required: false,
    maxLength: 250,
  },
  {
    name: 'bank_document',
    required: false,
    maxLength: 250,
  },
  {
    name: 'data_source_description',
    required: false,
    maxLength: 250,
  },
  {
    name: 'target',
    required: false,
    maxLength: 250,
  },
  {
    name: 'calibration_method',
    required: false,
    maxLength: 250,
  },
  {
    name: 'version_it_implementation',
    required: false,
    maxLength: 250,
  },
  {
    name: 'responsible_subdivision_and_project_lead_for_it_implementation',
    required: false,
    maxLength: 250,
  },
  {
    name: 'date_of_it_introduction_into_operation',
    required: false,
    maxLength: 250,
  },
  {
    name: 'psi_protocol',
    required: false,
    maxLength: 250,
  },
  {
    name: 'developing_start_date',
    required: false,
    maxLength: 250,
  },
  {
    name: 'developing_end_date',
    required: false,
    maxLength: 250,
  },
];

export const RATING_SYSTEM_REGULATOR_APPROVE_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'regulatory_code_rs_pvr',
    maxLength: 250,
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Модели ВПОДК',
        model_risk_type: 'Кредитный риск',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
    ],
  },
  {
    name: 'regulatory_code_model_pvr',
    maxLength: 250,
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Модели ВПОДК',
        model_risk_type: 'Кредитный риск',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
    ],
  },
  {
    name: 'internal_model_number',
    maxLength: 250,
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Модели ВПОДК',
        model_risk_type: 'Кредитный риск',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
    ],
  },
  {
    name: 'regulatory_class',
    maxLength: 250,
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Модели ВПОДК',
        model_risk_type: 'Кредитный риск',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
    ],
  },
  {
    name: 'regulatory_subclass',
    maxLength: 250,
    required: true,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
    requireConditions: [
      {
        model_type: 'Модели ВПОДК',
        model_risk_type: 'Кредитный риск',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
      {
        model_type: 'Риск-модели',
        model_risk_type: 'Кредитный риск',
        rating_model: 'Да',
        classification_of_rs_by_order_of_application_within_pvr:
          'Рейтинговые системы, подлежащие согласованию Регулятором',
      },
    ],
  },
  {
    name: 'regulatory_code_of_asset_class',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'method_calculation_model_parameter',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'importance_changes',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'approve_importance',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'approve_importance_changes',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'date_and_number_regulator_notification',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'date_submission_to_regulator',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'decision_date_and_number_of_application_model_for_segment',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'notification_date_and_number_of_application_model_for_segment',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },

  {
    name: 'decision_date_and_number_of_application_model',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'notification_date_and_number_of_application_model',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'start_date_of_application_model_approved_regulator',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
];

export const VALIDATION_MODEL_SCHEMA: FormFieldsSchema = [
  {
    name: 'validation_department',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },

  {
    name: 'plan_validation_type',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'validation_period',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'validation_report_approve_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'validation_result',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'auto_validation_result',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'validation_result_approve_date',
    required: false,
    customers: [CUSTOMER_MAP.UMRV],
  },
  {
    name: 'model_risk_coefficient',
    required: false,
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DIUR, CUSTOMER_MAP.DADM],
  },
];

const REST_MODEL_SCHEMA_BASE: FormFieldsSchema = [
  {
    name: 'rs_model_decommiss_date',
    customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
  },
];

export const REST_MODEL_SCHEMA: FormFieldsSchema = [
  ...ACTIVE_MODEL_SCHEMA,
  ...RATING_SYSTEM_MODEL_SCHEMA,
  ...RATING_SYSTEM_REGULATOR_APPROVE_MODEL_SCHEMA,
  ...REST_MODEL_SCHEMA_BASE,
].map((item) => ({
  name: item.name,
  maxLength: item.maxLength,
  required: false,
  alwaysDisabled: item.alwaysDisabled,
  customers: [CUSTOMER_MAP.UMRV, CUSTOMER_MAP.DADM],
}));

export const SUM_ARTEFACTS = [
  'Creator',
  'business_customer_departament',
  'Departament',
  'model_lang',
  'first_list_of_validation_tests',
  'mlflow_link',
  'entity_analysis_report',
  'aggregate_calculation_algorithm',
  'data_development_availability',
  'drp_load_successful_flg',
  'data_build_script_availible_ds_flg',
  'data_build_test_success',
  'data_build_script_test_result',
  'corrected_problem_formulation',
  'need_involve_de_flg',
  'long_datamart_build_script',
  'short_datamart_build_script',
  'pimi_psi',
  'target_variable_collecting_prototype_code',
  'developing_start_date',
  'developing_end_date',
  'model_data_07k_control',
  'model_data_07k_control_epic',
  'jupyter_notebook_link',
  'rstudio_link',
  'sas_link',
  'model_repository_link',
  'visualization',
  'requirements_for_model_monitoring',
  'model_binary_file',
  'vector_attributes',
  'analize_text_about_developing',
  'scoring_calculation_scripts',
  'previous_model_link',
  'total_scoring_calculation_scripts',
  'train_data_build_script',
  'snapshot_long_datamart',
  'callibration_type',
  'need_recreate_data_flg',
  'decision_of_model_efficiency_flg',
  'model_id',
  'product_name',
  'segment_name',
  'buiseness_process_name',
  'target_variable',
  'using_mode',
  'auto_correct_model',
  'plan_date_integration',
  'model_result_purpose',
  'model_result_purpose_comment',
  'significance_validity',
  'recreating_model_reason',
  'developing_model_reason',
  'order_for_developing_or_buiseness_case',
  'pilot_necessery',
  'model_type',
  'group_company',
  'model_category',
  'domain_knowledge',
  'task',
  'rating_system_name',
  'rating_system_description',
  'model_type_for_rating_system',
  'integration_necessery',
  'ds_lead',
  'de_lead',
  'mimp_lead',
  'modelops_lead',
  'dit_lead',
  'entity_attributes_list',
  'need_first_validation_flg',
  'need_actualize_arch_requirements_flg',
  'arch_requirements_file',
  'need_add_test_or_scenaries_flg',
  'problems_reveal_flg',
  'additional_analysis_and_recommendation',
  'first_validation_type',
  'need_involve_it_flg',
  'pilot_results_approving_flg',
  'need_update_arch_flg',
  'data_pilot_arch_requirements',
  'data_source_description',
  'target_variable_collecting_description',
  'need_interpretation_flg',
  'need_input_vector_flg',
  'input_output_vector_validation_scheme',
  'container_cfg_file',
  'model_image_nexus_link',
  'model_rest_service_test',
  'model_rest_service_prod',
  'etl_code_prom_datamart',
  'etl_code_monitoring_datamart',
  'prom_datamart_attributes',
  'br_monitoring_datamart',
  'monitoring_datamart_attributes',
  'datamart_need_involve_dit_flg',
  'integration_test_success_flg',
  'user_test_success_flg',
  'integration_decree_file',
  'integration_decree_date',
  'monitoring_requirements',
  'monitoring_description',
  'monitoring_plan_date',
  'monitoring_purpose',
  'monitoring_schedule',
  'monitoring_type',
  'deviation_significance_flg',
  'deviations_reveal_flg',
  'monitoring_report',
  'monitoring_results_comparasing',
  'master_scale',
  'monitoring_graphs',
  'monitoring_graphs_type',
  'monitoring_results_report',
  'uploading_data_link',
  'validator_lead',
  'conteiner_installing_test_flg',
  'is_model_interpreted_flg',
  'test_protocol_approving',
  'acceptance_tests_of_functional_testing',
  'methodological_tests_of_functional_testing',
  'functional_test_resuslt_analysis',
  'load_test_resuslt_analysis',
  'manual_test_resuslt_analysis',
  'psi_tests_protocol',
  'validator_additional_analysis',
  'deviations_during_validation_flg',
  'decision_of_model_completion_flg',
  'validation_tests',
  'ts_validation_tests_scenary',
  'plan_validation_type',
  'need_adding_validation_tests_flg',
  'auto_validation_report',
  'approving_autocorrect_changes_flg',
  'auto_monitoring_testing_flg',
  'drp_load_report',
  'entity_attributes_load_report',
  'removal_model_after_monitoring_flg',
  'script_calculation_algorithm',
  'integration_name',
  'data_name',
  'monitoring_name',
  'validation_name',
  'modeldev_name',
  'model_type_lev1',
  'model_deployment_approving_flg',
  'datamart_build_script',
  'datamart_link',
  'datamart_description',
  'autoupdating_datamart_script',
  'autoupdate_datamart_flg',
  'developing_model_datamart',
  'validation_model_datamart',
  'data_recreate_req',
  'features_algorithm_vector',
  'scenary_tech_specifiaction',
  'fisrt_validation_cfg',
  'fisrt_validation_template_report',
  'br_validation_datamart',
  'br_prom_datamart',
  'validation_datamart_attributes',
  'need_model_interpretation_flg',
  'model_after_interpretation',
  'decommission_order',
  'etl_code_validation_datamart',
  'spk_etl_prom',
  'spk_etl_monitoring',
  'spk_etl_validation',
  'check_list',
  'monitoring_scripts',
  'need_involve_dit_monitoring_flg',
  'pim_integration_flg',
  'requirements_approving_mipm_flg',
  'requirements_approving_de_flg',
  'need_correct_task_flg',
  'datamart_script_success_flg',
  'validation_parameters_approving_flg',
  'arch_requirements_agreement_mipm_flg',
  'arch_requirements_agreement_de_flg',
  'datamart_requirements_approving_mlops_flg',
  'datamart_requirements_approving_ds_flg',
  'validation_class_flg',
  'manual_first_validation_result',
  'manual_first_validation_report',
  'first_test_preprod_flg',
  'test_preprod_flg',
  'manual_validation_report',
  'manual_validation_decision_flg',
  'plan_validation_class_flg',
  'rollback_approve_ds_flg',
  'rollback_approve_mipm_flg',
  'rollback_approve_modelops_flg',
  'instance_rollback_approve_ds_flg',
  'instance_rollback_approve_mipm_flg',
  'ts_first_upload_file',
  'doc_rest_service',
  'spk_rest_service_doc',
  'integration_test_resuslt_analysis',
  'test_after_correct_model_bind_succes_flg',
  'protocol_after_correct_model_bind',
  'code_etl_model_monitoring',
  'pilot_results_approving_file',
  'analit_monitoring_link',
  'monitoring_option',
  'manual_validation_result',
  'validation_model_datamart_id',
  'validation_model_datamart_name',
  'developing_model_datamart_id',
  'developing_model_datamart_name',
  'prom_datamart_id',
  'prom_datamart_name',
  'validation_datamart_id',
  'validation_datamart_name',
  'monitoring_datamart_id',
  'monitoring_datamart_name',
  'sas_content_path',
  'sasid_diagram',
  'interpretation_model_lang',
  'bp_using_results_approving',
  'developing_report',
  'spk_etl_monitoring_process',
  'criterion_pilot_load',
  'criterion_file',
  'jira_interpretation_flg',
  'jira_cancel_analysis_flg',
  'jira_rollback',
  'auto_validation_result',
  'first_auto_validation_result',
  'first_auto_validation_report',
  'new_model_container',
  'validation_cfg',
  'business_customer_decision',
  'decision_of_model_completion',
  'cancel_development_reason',
  'cancel_ds_approve_flg',
  'cancel_mipm_approve_flg',
  'model_code',
  'decommision_request',
  'scripts_first_validation_tests',
  'scripts_validation_tests',
  'spk_rest_service',
  'imagePimNexusAddr',
  'containerCfgPimNexusAddr',
  'req_pilot_load',
  'sas_link_on_prod',
  'sas_link_on_test',
  'dockerCfgPimNexusAddr',
  'target',
  'score',
  'test_flg',
  'data_table_name',
  'score_points',
  'first_validation_config',
  'first_validation_spr_adr',
  'first_validation_data',
  'first_validation_data_developing',
  'first_validation_data_port',
  'first_validation_config',
  'first_validation_scale',
  'risk_scale_flg',
  'first_validation_priority',
  'developing_model_datamart_not_split',
  'integration_start_flg',
  'requirements_first_valid_datamart',
  'risk_scale_category',
  'risk_scale_brf_id',
  'risk_scale_type',
  'developing_mart_report',
  'risk_scale_end_date',
  'risk_scale_code',
  'risk_scale_code_from_guide',
  'risk_scale_parameter_type',
  'risk_scale_pa',
  'risk_scale_param_value_of_model',
  'risk_scale_order_value',
  'risk_scale_start_date',
  'model_customer',
  'automl_flg',
  'jira_request_link',
  'request_status',
  'jira_rollback',
  'description_data_model',
  'monitoring quality results',
  'data_build_test_success_ds',
  'model_container_automl',
  'automl_flg',
  'developing_report_automl',
  'model_file_automl',
  'requirements_for_quality_model_monitoring',
  'requirements_for_operational_model_monitoring',
  'development_results_approving_flg',
  'preliminarily_load_test_resuslt_analysis',
  'monitoring_datamart_script',
  'prom_datamart_script',
  'description_data_model_integration_datamart',
  'prom_datamart_report',
  'monitoring_datamart_report',
  'decision_of_model_integration_flg',
  'data_model',
  'description_data_source',
  'teamcity_integration_flg',
  'aggregate_calculation_algorithm_planned_validation',
  'datamart_description_planned_validation_de',
  'planned_validation_report',
  'planned_validation_script',
  'criterion_validation_datamart',
  'aggregate_calculation_algorithm_de',
  'additional_analytical_monitoring_flg',
  'requirements_additional_analytical_monitoring',
  'need_routine_update_flg',
  'test_planned_validation_datamart_validator_flg',
  'test_planned_validation_datamart_de_flg',
  'integration_autoupdating_datamart_script_add',
  'psi_protocol',
  'psi_results',
  'link_model_quality_monitoring',
  'monitoring_deviations',
  'link_nexus_docker_build_artifact',
  'link_bitbucket_code',
  'link_teamcity_build',
  'link_service_prod',
  'link_strategy_sas',
  'link_bitbucket_code_sas',
  'link_dag_file',
  'results_preliminary_functional_test',
  'specification_model',
  'first_validation_segment',
  'first_validation_model_type',
  'modification_datamart_use_model_flg',
  'modification_model_flg',
  'decisions_model_flg',
  'model_specifications_flg',
  'modification_architecture_flg',
  'architecture_requirements_flg',
  'criterion_architecture_requirements',
  'decisions_model_architecture_flg',
  'source_drp_flg',
  'datamart_developing_auto_renewable_flg',
  'attracting_dit_flg',
  'routine_update_flg',
  'attracting_dit_de_flg',
  'link_planned_validation_de',
  'need_involve_data_expert_flg',
  'data_expert_flg',
  'script_operational_monitor',
  'mr_sign_adjacency_model',
  'mr_sign_excessive_conservatism',
  'mr_last_validation_date',
  'mr_sign_ek',
  'id_model_validation',
  'integration_checklist',
  'date_completing_ds_tests',
  'calculation_mr_flg',
  'KUORR_number',
  'date_KUORR',
  'validation_result',
  'load_testing_result',
  'needed_updat_flg',
  'mr_test_result_1',
  'mr_comment_test_result_1',
  'mr_test_result_1_ds',
  'mr_comment_test_result_1_ds',
  'mr_test_result_2',
  'mr_comment_test_result_2',
  'mr_test_result_2_ds',
  'mr_comment_test_result_2_ds',
  'mr_test_result_3',
  'mr_comment_test_result_3',
  'mr_test_result_3_ds',
  'mr_comment_test_result_3_ds',
  'mr_test_result_4',
  'mr_comment_test_result_4',
  'mr_test_result_4_ds',
  'mr_comment_test_result_4_ds',
  'mr_test_result_5',
  'mr_comment_test_result_5',
  'mr_test_result_5_ds',
  'mr_comment_test_result_5_ds',
  'mr_test_result_6',
  'mr_comment_test_result_6',
  'mr_test_result_6_ds',
  'mr_comment_test_result_6_ds',
  'mr_test_result_7',
  'mr_comment_test_result_7',
  'mr_test_result_7_ds',
  'mr_comment_test_result_7_ds',
  'mr_test_result_8',
  'mr_comment_test_result_8',
  'mr_test_result_8_ds',
  'mr_comment_test_result_8_ds',
  'mr_test_result_9',
  'mr_comment_test_result_9',
  'mr_test_result_10',
  'mr_comment_test_result_10',
  'mr_test_result_11',
  'mr_comment_test_result_11',
  'mr_test_result_12',
  'mr_comment_test_result_12',
  'mr_rate_segment',
  'mr_rate_a_obsolescence',
  'mr_ratio_k_validation',
  'mr_ratio_k_develop',
  'mr_ratio_k_result',
  'mr_ratio_k_process_analysis',
  'mr_rate_k',
  'mr_ratio_k_proces_models',
  'mr_rate_adjacency',
  'mr_ratio_k_final_obsolescence',
  'pimi_psi_datamart',
  'ts_validation_tests_scenary2',
  'data_build_script_availible_de_flg',
  'data_build_test_success_de',
  'link_bitbucket_code_batch',
  'implementation_document_flg',
  'requirements_uploading_drp',
  'assignment_reopen_comment',
  'assignment_complete_comment',
  'assignment_complete_report',
  'assignment_complete_link',
  'assignment_text',
  'assignment_number',
  'assignment_protocol_details',
  'assignment_uo_name',
  'assignment_uo_question',
  'assignment_department',
  'assignment_end_date_flg',
  'assignment_end_date_text',
  'assignment_status_reason_text',
  'assignment_status_reason_file',
  'assignment_model',
  'assignment_model_risk',
  'assignment_risk_type',
  'assignment_contractor',
  'assignment_end_date',
  'need_recreate_data_flg2',
  'decision_of_model_completion_doc',
  'data_development_availability2',
  'deviation_significance_flg2',
  'remove_development_reason',
  'remove_ds_approve_flg',
  'remove_mipm_approve_flg',
  'model_algorithm',
  'model_is_used',
  'implementation_decision',
  'model_indicator',
  'implementation_segment',
  'implementation_validity',
  'validity_approve',
  'approve_date',
  'remove_decision',
  'validation_department',
  'validation_period',
  'validation_report_approve_date',
  'validation_result_approve_date',
  'importance_changes',
  'approve_importance',
  'approve_importance_changes',
  'model_risk_type',
  'model_changes_info',
  'responsible_for_significance_validity',
  'provides_piloting',
  'operational_monitoring',
  'analytical_monitoring',
  'rfd',
  'need_plan_validation_flg',
  'dev_model_status_flg',
  'data_development_availability3',
  'need_involve_de_flg2',
  'datamart_name',
  'datamart_desc',
  'dapp_load_successful_flg',
  'model_epic_04',
  'model_epic_04_date',
  'datamart_script_success_ds_flg',
  'datamart_script_success_de_flg',
  'datamart_pilot_de_flg',
  'model_code_link',
  'pilot_model_developing_flg',
  'end_pilot_model_developing_flg',
  'model_epic_05a',
  'data_completion_of_stage_05a',
  'decision_pilot_model_flg',
  'model_epic_05',
  'feature_service_link',
  'need_piloting_prototype_stand_flg',
  'dev_pilot_operation_ds_flg',
  'model_development_results_approving_flg',
  'need_prom_datamart_developing_flg',
  'implementation_doc_set_file',
  'validation_period',
  'deviations_during_validation2_flg',
  'first_validation_tests_result',
  'sfera_code_validation_link',
  'decision_of_model_integration',
  'prom_datamart_source_desc',
  'prom_datamart_link',
  'prom_datamart_link_dag_file',
  'prom_datamart_pilot_de_flg',
  'model_epic_07',
  'model_epic_07_date',
  'prom_datamart_ready_to_preprod_flg',
  'need_additional_datamart_dev_flg',
  'full_validation_execution_order_comment_flg',
  'plan_validation_datamart_name',
  'plan_validation_datamart_desc',
  'plan_validation_datamart_link',
  'plan_validation_datamart_dag_link',
  'plan_validation_datamart_decision',
  'requirements_plan_validation_datamart',
  'plan_validation_datamart_developer_flg',
  'finish_datamart_prototype_flg',
  'finish_test_datamart_dev_flg',
  'model_integration_mode_flg',
  'model_service_dev_link',
  'need_pilot_dev_flg',
  'model_integration_dag_link',
  'model_integration_outside_pim_flg',
  'model_pilot_dev_flg',
  'final_version_spec',
  'transfer_to_preprod_datamart_build_dag_flg',
  'preprod_test_datamart_flg',
  'preprod_psi_datamart_link',
  'transfer_to_prod_datamart_build_dag_flg',
  'transfer_to_preprod_model_artefacts_flg',
  'preprod_test_model_flg',
  'preprod_psi_model_link',
  'release',
  'model_epic_09',
  'model_epic_11',
  'model_epic_11_date',
  'date_of_introduction_into_operation',
  'tranfer_model_prod_flg',
  'customer_model_id',
  'full_validation_department',
  'full_validation_type',
  'full_validation_period',
  'full_validation_rs_model_result',
  'full_validation_report_approve_date',
  'full_validation_result_approve_date',
  'deviations_during_full_validation_flg',
  'full_validation_tests_result',
  'full_validation_report',
  'full_validation_additional_analysis_and_recommendation',
  'full_validation_cfg',
  'signifiance_deviations_flg',
  'decision_of_model_owner_file',
  'model_decommiss_confirm_flg',
  'rs_model_decommiss_date',
  'model_decommiss_confirm_file',
  'model_product_flg',
  'model_validation_status_flg',
  'fast_model_integration_datamart_flg',
  'fast_model_developing_datamart_flg',
  'fast_first_model_validation_flg',
  'fast_model_decision_flg',
  'ts_upload_data_file',
  'model_epic_12',
  'model_epic_12_date',
  'model_epic_05_date',
  'model_first_validation_status_flg',
  'fast_model_integration_mode_flg',
  'statement_reg_is_req_flg',
  'current_model_stage_executor',
  'model_desc',
  'source_code_link',
  'build_link',
  'docker_artifact_link',
  'data_lineage_ml_link',
  'devsecops_project_area',
  'code_repository_uri',
  'release_branch',
  'deployment_channel',
  'output_table',
  'allocation_assessment_class',
  'allocation_assessment_parameters',
  'project_ref',
  'dev_team',
  'deploy_team',
  'runtime_subsystem'
]
