import { ArtificialRow, COLUMN_TYPE, Column, ColumnsFilter } from '@shared/types';

export const initialColumns: Array<Column> = [
  {
    name: 'system_model_id',
    title: 'Идентификатор версии модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'group_company',
    title: 'Компания группы',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'update_date',
    title: 'Отчетная дата / дата последних изменений информации о Модели',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_alias',
    title: 'Алиас модели',
    type: COLUMN_TYPE.LINK,
  },
  {
    name: 'model_id',
    title: 'Идентификатор Модели / ID',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_version',
    title: 'Версия модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_version_validation',
    title: 'Версия Модели от владельца',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_name_validation',
    title: 'Название модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_desc',
    title: 'Описание модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_type',
    title: 'Тип модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_risk_type',
    title: 'Вид / подвид риска',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'business_model_risk_subtype',
    title: 'Подвид риска, для оценки которого применяется Модель / Подтип Бизнес-модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'business_customer',
    title: 'Владелец Модели / Алгоритма',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'business_customer_departament',
    title: 'Подразделение Владельца Модели / Алгоритма',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'significance_validity',
    title: 'Уровень значимости Модели / РС',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'implementation_validity',
    title: 'Утверждение РС / Модели / Алгоритма в эксплуатацию',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_changes_info',
    title: 'Краткая информация о решениях по изменению Модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'ds_department',
    title: 'Подразделение разработки и вендор',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'developing_end_date',
    title: 'Дата окончания разработки Модели',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'record_id',
    title: 'ID записи',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'rating_system_name',
    title: 'Название Рейтинговой системы',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'regulatory_code_rs_pvr',
    title: 'Регуляторный код РС (ПВР)',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'description_rating_system',
    title: 'Описание Рейтинговой системы',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'identifier_model_algorithm_for_rwa',
    title: 'Идентификатор Модели / Алгоритма для целей RWA',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'regulatory_code_model_pvr',
    title: 'Регуляторный код Модели (ПВР)',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'internal_model_number',
    title: 'Внутренний номер модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'active_model',
    title: 'Действующая модель/ модуль',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'rating_model',
    title: 'Модель входит в рейтинговую систему?',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_indicator',
    title: 'Индикатор модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'calibration_version',
    title: 'Версия калибровки',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'calibration_date',
    title: 'Дата калибровки',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'regulatory_code_of_asset_class',
    title: 'Регуляторный код класса/подкласса активов',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_id_from_model_owner',
    title: 'Идентификатор Модели / Алгоритма от Владельца модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'classification_rs_algorithm_by_asset_classes',
    title: 'Классификация РС / Алгоритма по классам активов',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'degree_of_regulatory_supervision',
    title: 'Степень регуляторного надзора',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'materiality_rate',
    title: 'Уровень материальности',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'impact_coverage',
    title: 'Охват последствий',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'responsible_for_significance_validity',
    title: 'Кем определен уровень значимости Модели / РС',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'classification_of_rs_by_order_of_application_within_pvr',
    title: 'Классификация РС по порядку применения в рамках ПВР',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'credit_risk_component',
    title: 'Компонент кредитного риска',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'method_calculation_model_parameter',
    title: 'Метод расчета параметра Модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'segment_name',
    title: 'Целевой сегмент Модели / Алгоритма',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'implementation_segment',
    title: 'Сегмент применения Модели / Рейтинговой системы / Алгоритма',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'regulatory_class',
    title: 'Регуляторный класс',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'regulatory_subclass',
    title: 'Регуляторный подкласс кредитных требований',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'goals_using_results_of_work_rs',
    title: 'Для каких целей происходит использование результатов работы РС',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'usage_confirm_date_q1',
    title: 'Дата подтверждения использования в Q1',
    type: COLUMN_TYPE.QUARTERLY_DATE,
  },
  {
    name: 'usage_confirm_date_q2',
    title: 'Дата подтверждения использования в Q2',
    type: COLUMN_TYPE.QUARTERLY_DATE,
  },
  {
    name: 'usage_confirm_date_q3',
    title: 'Дата подтверждения использования в Q3',
    type: COLUMN_TYPE.QUARTERLY_DATE,
  },
  {
    name: 'usage_confirm_date_q4',
    title: 'Дата подтверждения использования в Q4',
    type: COLUMN_TYPE.QUARTERLY_DATE,
  },
  {
    name: 'usage_confirm_flag_q1',
    title: 'Модель используется заказчиком в Q1',
    type: COLUMN_TYPE.QUARTERLY_FLAG,
  },
  {
    name: 'usage_confirm_flag_q2',
    title: 'Модель используется заказчиком в Q2',
    type: COLUMN_TYPE.QUARTERLY_FLAG,
  },
  {
    name: 'usage_confirm_flag_q3',
    title: 'Модель используется заказчиком в Q3',
    type: COLUMN_TYPE.QUARTERLY_FLAG,
  },
  {
    name: 'usage_confirm_flag_q4',
    title: 'Модель используется заказчиком в Q4',
    type: COLUMN_TYPE.QUARTERLY_FLAG,
  },
  {
    name: 'allocation_kib_usage',
    title: 'Аллокация применения КИБ',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_smb_usage',
    title: 'Аллокация применения СМБ',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_rb_usage',
    title: 'Аллокация применения РБ',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_kc_usage',
    title: 'Аллокация применения КЦ',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_other_usage',
    title: 'Аллокация применения Другое',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_kib_comment',
    title: 'Комментарий к аллокации КИБ',
    type: COLUMN_TYPE.PERCENT_NUMBER,
  },
  {
    name: 'allocation_smb_comment',
    title: 'Комментарий к аллокации СМБ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'allocation_rb_comment',
    title: 'Комментарий к аллокации РБ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'allocation_kc_comment',
    title: 'Комментарий к аллокации КЦ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'allocation_other_comment',
    title: 'Комментарий к аллокации Другое',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validity_approve',
    title: 'Решение об утверждении РС / Модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validity_approve_date',
    title: 'Дата утверждения РС / Модели / Алгоритма',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'bank_document',
    title: 'Банковский документ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'rs_model_decommiss_date',
    title: 'Дата выведения Модели из ПИМ',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'remove_decision',
    title: 'Реквизиты решения о выведении из эксплуатации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'remove_date_validation',
    title: 'Дата выведения РС / Модели из эксплуатации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'assignment_contractor',
    title: 'Исполнитель',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'developing_start_date',
    title: 'Дата начала разработки Модели',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'data_source_description',
    title: 'Основные источники данных',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'target',
    title: 'Целевая переменная',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'calibration_method',
    title: 'Метод Калибровки',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'developing_report',
    title: 'Отчет по разработке',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'name_and_version_rating_system',
    title: 'Название и версия ИТ системы рейтингования',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'version_it_implementation',
    title: 'Версия ИТ реализации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'responsible_subdivision_and_project_lead_for_it_implementation',
    title: 'Ответственное подразделение и руководитель проекта внедрения ИТ реализации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'date_of_it_introduction_into_operation',
    title: 'Дата внедрения в промышленную эксплуатацию ИТ реализации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'psi_protocol',
    title: 'Протокол ПСИ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validation_department',
    title: 'Подразделение, проводившее валидацию',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'plan_validation_type',
    title: 'Вид валидации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validation_period',
    title: 'Период проведения валидации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validation_report_approve_date',
    title: 'Дата утверждения отчета валидации',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'validation_result',
    title: 'Результат валидации РС / Модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'validation_result_approve_date',
    title:
      'Информация о дате утверждения на УО МР текущих (действующих) агрегированных результатов валидации',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'auto_validation_result',
    title: 'Отчет по валидации',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'importance_changes',
    title: 'Существенность внесенных измененией в РС',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'approve_importance',
    title: 'Утверждение уровня существенности',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'approve_importance_changes',
    title: 'Решение об утверждении уровня существенности',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'date_submission_to_regulator',
    title: 'Дата подачи заявки Регулятору',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'decision_date_and_number_of_application_model_for_segment',
    title:
      'Дата и номер решения Регулятора о выдаче разрешения на применение РС/Модели для сегмента',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'date_and_number_regulator_notification',
    title: 'Дата и номер уведомления Регулятора',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'decision_date_of_application_model_for_segment',
    title: 'Дата решения БР о выдаче разрешения на применение РС / Модели для сегмента',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'decision_number_of_application_model_for_segment',
    title: 'Номер решения БР о выдаче разрешения на применение РС / Модели для сегмента',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'notification_date_and_number_of_application_model_for_segment',
    title: 'Дата и номер уведомления в адрес Регулятора о применении РС / Модели для сегмента',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'notification_date_of_application_model_for_segment',
    title: 'Дата уведомления БР о применении РС / Модели для сегмента',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'notification_number_of_application_model_for_segment',
    title: 'Номер уведомления БР о применении РС / Модели для сегмента',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'decision_date_and_number_of_application_model',
    title:
      'Дата и номер первичного решения Регулятора о выдаче разрешения на применение РС/Модели (для всех сегментов)',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'decision_date_of_application_model',
    title: 'Дата решения БР о выдаче разрешения на применение РС / Модели',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'decision_number_of_application_model',
    title: 'Номер решения БР о выдаче разрешения на применение РС / Модели',
    type: COLUMN_TYPE.STRING,
  },

  {
    name: 'notification_date_and_number_of_application_model',
    title:
      'Дата и номер уведомления в адрес Регулятора о начале первичного применения РС/Модели (для всех сегментов)',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'notification_date_of_application_model',
    title: 'Дата уведомления БР о применении РС / Модели',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'notification_number_of_application_model',
    title: 'Номер уведомления БР о применении РС / Модели',
    type: COLUMN_TYPE.STRING,
  },

  {
    name: 'start_date_of_application_model_approved_regulator',
    title: 'Дата начала применения РС / Модели, утвержденная Регулятором',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_crs_code',
    title: 'Код модели ЦРС',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'rfd',
    title: 'RFD',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_name',
    title: 'Название модели в реестре ДАДМ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'ds_stream',
    title: 'Стрим-исполнитель',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_04',
    title: 'Этап 04',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_04_date',
    title: 'Дата решения 04',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_epic_05',
    title: 'Модельный эпик 05',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_05a',
    title: 'Этап 05А',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'data_completion_of_stage_05a',
    title: 'Дата завершения разработки пилота',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'solution_to_implement_model',
    title: 'Решение о внедрении модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_07',
    title: 'Этап 07',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_07_date',
    title: 'Дата решения для 07 этапа',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'customer_model_id',
    title: 'CustomModelId',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_algorithm',
    title: 'ModelType',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'release',
    title: 'Релиз',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_09',
    title: 'Эпик 09',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_11',
    title: 'Эпик 11',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_11_date',
    title: 'Дата решения для эпика 11',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_epic_12',
    title: 'Этап 12',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_epic_12_date',
    title: 'Дата решения для эпика 12',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'date_of_introduction_into_operation',
    title: 'Дата релиза',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_status',
    title: 'Этап ЖЦМ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'model_status_assignee',
    title: 'Исполнитель текущего этапа ЖЦМ',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'developing_model_reason',
    title: 'Основание для разработки',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'pvr',
    title: 'ПВР',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'create_date',
    title: 'Дата создания',
    type: COLUMN_TYPE.DATE,
  },
  {
    name: 'model_source',
    title: 'Система источник данных',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'relations',
    title: '',
    width: '48px',
    sticky: true,
    type: COLUMN_TYPE.ACTION,
  },
  {
    name: 'reason_model_delete',
    title: 'Причина удаления модели',
    type: COLUMN_TYPE.STRING,
  },
  {
    name: 'status',
    title: 'Cтатус',
    type: COLUMN_TYPE.STRING,
  },
];

export const initialColumnsFilters: Omit<ColumnsFilter, keyof ArtificialRow> = {
  system_model_id: [],
  group_company: [],
  update_date: [],
  model_alias: [],
  model_id: [],
  model_version: [],
  model_version_validation: [],
  model_name_validation: [],
  model_desc: [],
  model_type: [],
  model_risk_type: [],
  business_model_risk_subtype: [],
  business_customer: [],
  business_customer_departament: [],
  significance_validity: [],
  implementation_validity: [],
  model_changes_info: [],
  ds_department: [],
  developing_end_date: [],
  record_id: [],
  rating_system_name: [],
  regulatory_code_rs_pvr: [],
  description_rating_system: [],
  identifier_model_algorithm_for_rwa: [],
  regulatory_code_model_pvr: [],
  internal_model_number: [],
  active_model: [],
  rating_model: [],
  model_indicator: [],
  calibration_version: [],
  calibration_date: [],
  regulatory_code_of_asset_class: [],
  model_id_from_model_owner: [],
  classification_rs_algorithm_by_asset_classes: [],
  degree_of_regulatory_supervision: [],
  materiality_rate: [],
  impact_coverage: [],
  responsible_for_significance_validity: [],
  classification_of_rs_by_order_of_application_within_pvr: [],
  credit_risk_component: [],
  method_calculation_model_parameter: [],
  segment_name: [],
  implementation_segment: [],
  regulatory_class: [],
  regulatory_subclass: [],
  goals_using_results_of_work_rs: [],
  usage_confirm_date_q1: [],
  usage_confirm_date_q2: [],
  usage_confirm_date_q3: [],
  usage_confirm_date_q4: [],
  usage_confirm_flag_q1: [],
  usage_confirm_flag_q2: [],
  usage_confirm_flag_q3: [],
  usage_confirm_flag_q4: [],
  allocation_kib_usage: [],
  allocation_smb_usage: [],
  allocation_rb_usage: [],
  allocation_kc_usage: [],
  allocation_other_usage: [],
  allocation_kib_comment: [],
  allocation_smb_comment: [],
  allocation_rb_comment: [],
  allocation_kc_comment: [],
  allocation_other_comment: [],
  create_date: [],
  validity_approve: [],
  validity_approve_date: [],
  bank_document: [],
  rs_model_decommiss_date: [],
  remove_decision: [],
  remove_date_validation: [],
  assignment_contractor: [],
  developing_start_date: [],
  data_source_description: [],
  target: [],
  calibration_method: [],
  developing_report: [],
  name_and_version_rating_system: [],
  version_it_implementation: [],
  responsible_subdivision_and_project_lead_for_it_implementation: [],
  date_of_it_introduction_into_operation: [],
  psi_protocol: [],
  validation_department: [],
  plan_validation_type: [],
  validation_period: [],
  validation_report_approve_date: [],
  validation_result: [],
  validation_result_approve_date: [],
  auto_validation_result: [],
  importance_changes: [],
  approve_importance: [],
  approve_importance_changes: [],
  date_submission_to_regulator: [],
  decision_date_and_number_of_application_model_for_segment: [],
  date_and_number_regulator_notification: [],
  decision_date_of_application_model_for_segment: [],
  decision_number_of_application_model_for_segment: [],
  notification_date_and_number_of_application_model_for_segment: [],
  notification_date_of_application_model_for_segment: [],
  notification_number_of_application_model_for_segment: [],
  decision_date_and_number_of_application_model: [],
  decision_date_of_application_model: [],
  decision_number_of_application_model: [],
  notification_date_and_number_of_application_model: [],
  notification_date_of_application_model: [],
  notification_number_of_application_model: [],
  start_date_of_application_model_approved_regulator: [],
  model_crs_code: [],
  rfd: [],
  model_name: [],
  ds_stream: [],
  model_epic_04: [],
  model_epic_04_date: [],
  model_epic_05: [],
  model_epic_05a: [],
  data_completion_of_stage_05a: [],
  solution_to_implement_model: [],
  model_epic_07: [],
  model_epic_07_date: [],
  customer_model_id: [],
  model_algorithm: [],
  release: [],
  model_epic_09: [],
  model_epic_11: [],
  model_epic_11_date: [],
  model_epic_12: [],
  model_epic_12_date: [],
  date_of_introduction_into_operation: [],
  model_status: [],
  model_status_assignee: [],
  pvr: [],
  model_source: [],
  id: [],
  root_model_id: [],
  model_version_id: [],
  uuid: [],
  product_name: [],
  developing_model_reason: [],
  provides_piloting: [],
  operational_monitoring: [],
  analytical_monitoring: [],
  artefacts_model_id: [],
  business_status: [],
  lead_validator_comment_model_delete: [],
  lead_validator_resolution_model_delete: [],
  model_creator: [],
  reason_model_delete: [],
  status: [],
  analize_text_about_developing: [],
  model_name_dadm: [],
  custom_model_id: [],
  custom_model_type: [],
};

