enum RIGHT_PANEL_TYPE {
  ADD_MODEL = 'ADD_MODEL',
  EDIT_MODEL = 'EDIT_MODEL',
  HISTORY_CHANGES = 'HISTORY_CHANGES',
  ADD_TEMPLATE = 'ADD_TEMPLATE',
  DELETE_MODEL = 'DELETE_MODEL',
}

enum ACTIVE_SCREEN {
  TABLE = 'TABLE',
  TEMPLATE_FILTERS = 'TEMPLATE_FILTERS',
  COMPARE = 'COMPARE',
}

enum MODEL_FORM_MODE {
  ADD = 'ADD',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
}

export { RIGHT_PANEL_TYPE, ACTIVE_SCREEN, MODEL_FORM_MODE };

