enum RIGHT_PANEL_TYPE {
  ADD_MODEL = 'ADD_MODEL',
  EDIT_MODEL = 'EDIT_MODEL',
  HISTORY_CHANGES = 'HISTORY_CHANGES',
  ADD_TEMPLATE = 'ADD_TEMPLATE',
  DELETE_MODEL = 'DELETE_MODEL',
}

enum MODEL_FORM_MODE {
  ADD = 'ADD',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  DELETE_CONFIRM = 'DELETE_CONFIRM',
}

export { RIGHT_PANEL_TYPE, MODEL_FORM_MODE };

