export enum API_ROUTES {
  MODELS = '/models',
  MODELS_EDIT = '/models/update',
  COMPARE_MODELS = '/models/compare',
  MODEL_ADD = '/model/create',
  MODEL_RELATIONS = '/model/relations',
  MODEL_ARTIFACT_HISTORY = '/model/artefact/history',
  TEMPLATES = '/templates',
  TEMPLATE_ADD = '/template/create',
  TEMPLATE_EDIT = '/template/update',
  TEMPLATE_DELETE = '/template/delete',
  ARTIFACTS = '/artefacts',
  ARTIFACTS_EDIT = '/artefacts/update',
  REPORT = '/report',
  REPORT_DOWNLOAD = '/reports/download',
  METRICS = '/metrics',
  METRICS_EXPORT = '/metrics/export',
  BI_DATAMART_SYNC_MODELS = '/bi-datamart/sync/models',
  BI_DATAMART_SYNC_TASKS = '/bi-datamart/sync/tasks',
  BI_DATAMART_STATUS = '/bi-datamart/status',
}
