export enum API_ROUTES {
  MODELS = '/models',
  MODELS_EDIT = '/models/update',
  COMPARE_MODELS = '/models/compare',
  MODEL_ADD = '/model/create',
  MODEL_ARTIFACT_HISTORY = '/model/artefact/history',
  TEMPLATES = '/templates',
  TEMPLATE_ADD = '/template/create',
  TEMPLATE_EDIT = '/template/update',
  TEMPLATE_DELETE = '/template/delete',
  ARTIFACTS = '/artefacts',
  ARTIFACTS_EDIT = '/artefacts/update',
  REPORT = '/report',
  METRICS = '/metrics',
}
